# Code generated by wasm_pybindgen; DO NOT EDIT.

import argparse
import pathlib

from ._client import JouleQuestWasm

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        usage="Validates that the wasm provides the expected API"
    )
    parser.add_argument(
        "--wasm", type=pathlib.Path, required=True, help="Path to compiled wasm binary"
    )
    parser.add_argument(
        "--play", action="store_true", default=False, help="Instantiate and call some functions"
    )
    args = parser.parse_args()

    with JouleQuestWasm(args.wasm) as jq:
        print(f"{args.wasm} implements the expected API")
        if args.play:
            game = jq.instance()
            game.reset(num_players=4)
            game.set_rng_seed(0)

            assert game.game_status() == 0
            assert game.round() == 1
            assert game.num_players() == 4

            max_action = game.max_action()
            print(f"Player 0 initial action mask: {game.possible_actions_mask(0):0{max_action}b}")
            code = game.can_perform_action(player_index=0, action_int=14)
            assert code == 0  # ErrCode.OK

            code = game.apply_action(player_index=0, action_int=14)
            assert code == 0  # ErrCode.OK

            code = game.can_perform_action(player_index=0, action_int=14)
            assert code == 2  # ErrCode.InvalidAction

            print(f"Player 0 action mask after playing action=14: {game.possible_actions_mask(0):0{max_action}b}")
