// Code generated by "stringer -type=ActionType -trimprefix=ActionType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ActionTypeBuildAsset-0]
	_ = x[ActionTypeScrapAsset-1]
	_ = x[ActionTypeTakeoverAsset-2]
	_ = x[ActionTypeTakeoverScrapAsset-3]
	_ = x[ActionTypePledgeCapacity-4]
	_ = x[ActionTypeFinished-5]
}

const _ActionType_name = "BuildAssetScrapAssetTakeoverAssetTakeoverScrapAssetPledgeCapacityFinished"

var _ActionType_index = [...]uint8{0, 10, 20, 33, 51, 65, 73}

func (i ActionType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ActionType_index)-1 {
		return "ActionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActionType_name[_ActionType_index[idx]:_ActionType_index[idx+1]]
}
