// Code generated by "stringer -type=EventRisk -trimprefix=EventRisk"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventRiskLow-0]
	_ = x[EventRiskMedium-1]
	_ = x[EventRiskHigh-2]
}

const _EventRisk_name = "LowMediumHigh"

var _EventRisk_index = [...]uint8{0, 3, 9, 13}

func (i EventRisk) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EventRisk_index)-1 {
		return "EventRisk(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventRisk_name[_EventRisk_index[idx]:_EventRisk_index[idx+1]]
}
