// Code generated by "stringer -type=GameLogEvent -trimprefix=GameLogEvent"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GameLogEventStateMachineTransition-0]
	_ = x[GameLogEventPlayerAction-1]
	_ = x[GameLogEventPlayerActionInvalid-2]
	_ = x[GameLogEventEventDrawn-3]
	_ = x[GameLogEventGridOutcome-4]
	_ = x[GameLogEventMarketOutcome-5]
	_ = x[GameLogEventCarbonTaxApplied-6]
	_ = x[GameLogEventPlayerLoses-7]
	_ = x[GameLogEventEveryoneLoses-8]
	_ = x[GameLogEventGlobalWin-9]
}

const _GameLogEvent_name = "StateMachineTransitionPlayerActionPlayerActionInvalidEventDrawnGridOutcomeMarketOutcomeCarbonTaxAppliedPlayerLosesEveryoneLosesGlobalWin"

var _GameLogEvent_index = [...]uint8{0, 22, 34, 53, 63, 74, 87, 103, 114, 127, 136}

func (i GameLogEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameLogEvent_index)-1 {
		return "GameLogEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameLogEvent_name[_GameLogEvent_index[idx]:_GameLogEvent_index[idx+1]]
}
