// Code generated by "stringer -type=GameLogEvent -trimprefix=GameLogEvent"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GameLogEventStateMachineTransition-0]
	_ = x[GameLogEventPlayerBuildAsset-1]
	_ = x[GameLogEventPlayerTakeoverAsset-2]
	_ = x[GameLogEventPlayerScrapAsset-3]
	_ = x[GameLogEventPlayerPledgeCapacity-4]
	_ = x[GameLogEventPlayerBuyService-5]
	_ = x[GameLogEventPlayerDoneBuildPhase-6]
	_ = x[GameLogEventEventDrawn-7]
	_ = x[GameLogEventGridOutcome-8]
	_ = x[GameLogEventMarketOutcome-9]
	_ = x[GameLogEventCarbonTaxApplied-10]
	_ = x[GameLogEventPlayerLoses-11]
	_ = x[GameLogEventEveryoneLoses-12]
	_ = x[GameLogEventGlobalWin-13]
}

const _GameLogEvent_name = "StateMachineTransitionPlayerBuildAssetPlayerTakeoverAssetPlayerScrapAssetPlayerPledgeCapacityPlayerBuyServicePlayerDoneBuildPhaseEventDrawnGridOutcomeMarketOutcomeCarbonTaxAppliedPlayerLosesEveryoneLosesGlobalWin"

var _GameLogEvent_index = [...]uint8{0, 22, 38, 57, 73, 93, 109, 129, 139, 150, 163, 179, 190, 203, 212}

func (i GameLogEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameLogEvent_index)-1 {
		return "GameLogEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameLogEvent_name[_GameLogEvent_index[idx]:_GameLogEvent_index[idx+1]]
}
