// Code generated by "stringer -type=GameStatus -trimprefix=GameStatus"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GameStatusOngoing-0]
	_ = x[GameStatusWin-1]
	_ = x[GameStatusLoss-2]
}

const _GameStatus_name = "OngoingWinLoss"

var _GameStatus_index = [...]uint8{0, 7, 10, 14}

func (i GameStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameStatus_index)-1 {
		return "GameStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameStatus_name[_GameStatus_index[idx]:_GameStatus_index[idx+1]]
}
