// Code generated by "stringer -type=LossCondition -trimprefix=LossCondition"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LossConditionNone-0]
	_ = x[LossConditionPlayerBankrupt-1]
	_ = x[LossConditionLastPlayerWithFossilAssets-2]
	_ = x[LossConditionGridUnstable-3]
	_ = x[LossConditionInsufficientGeneration-4]
	_ = x[LossConditionCarbonEmissionsExceeded-5]
	_ = x[LossConditionNoActivePlayers-6]
	_ = x[LossConditionUnownedTakeoverAssets-7]
}

const _LossCondition_name = "NonePlayerBankruptLastPlayerWithFossilAssetsGridUnstableInsufficientGenerationCarbonEmissionsExceededNoActivePlayersUnownedTakeoverAssets"

var _LossCondition_index = [...]uint8{0, 4, 18, 44, 56, 78, 101, 116, 137}

func (i LossCondition) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LossCondition_index)-1 {
		return "LossCondition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LossCondition_name[_LossCondition_index[idx]:_LossCondition_index[idx+1]]
}
