// Code generated by "stringer -type=PlayerStatus -trimprefix=PlayerStatus"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PlayerStatusActive-0]
	_ = x[PlayerStatusLost-1]
}

const _PlayerStatus_name = "ActiveLost"

var _PlayerStatus_index = [...]uint8{0, 6, 10}

func (i PlayerStatus) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PlayerStatus_index)-1 {
		return "PlayerStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PlayerStatus_name[_PlayerStatus_index[idx]:_PlayerStatus_index[idx+1]]
}
