// Code generated by "stringer -type=StateMachineState -trimprefix=GameState"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateMachineStateGameStart-0]
	_ = x[StateMachineStateRoundStart-1]
	_ = x[StateMachineStateBuildPhase-2]
	_ = x[StateMachineStateOperatePhase-3]
	_ = x[StateMachineStateRoundEnd-4]
	_ = x[StateMachineStateGameEnd-5]
}

const _StateMachineState_name = "StateMachineStateGameStartStateMachineStateRoundStartStateMachineStateBuildPhaseStateMachineStateOperatePhaseStateMachineStateRoundEndStateMachineStateGameEnd"

var _StateMachineState_index = [...]uint8{0, 26, 53, 80, 109, 134, 158}

func (i StateMachineState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_StateMachineState_index)-1 {
		return "StateMachineState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StateMachineState_name[_StateMachineState_index[idx]:_StateMachineState_index[idx+1]]
}
