// Code generated by "stringer -type=CapacityRule -trimprefix=CapacityRule"; DO NOT EDIT.

package params

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CapacityRulePaymentPerAsset-0]
	_ = x[CapacityRuleNoCapacityMarket-1]
	_ = x[CapacityRuleSharedCapacityPaymentPool-2]
}

const _CapacityRule_name = "PaymentPerAssetNoCapacityMarketSharedCapacityPaymentPool"

var _CapacityRule_index = [...]uint8{0, 15, 31, 56}

func (i CapacityRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CapacityRule_index)-1 {
		return "CapacityRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CapacityRule_name[_CapacityRule_index[idx]:_CapacityRule_index[idx+1]]
}
