// Code generated by "stringer -type=CarbonTaxRule -trimprefix=CarbonTaxRule"; DO NOT EDIT.

package params

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CarbonTaxRuleNoCarbonTax-0]
	_ = x[CarbonTaxRuleApplyCarbonTax-1]
}

const _CarbonTaxRule_name = "NoCarbonTaxApplyCarbonTax"

var _CarbonTaxRule_index = [...]uint8{0, 11, 25}

func (i CarbonTaxRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_CarbonTaxRule_index)-1 {
		return "CarbonTaxRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CarbonTaxRule_name[_CarbonTaxRule_index[idx]:_CarbonTaxRule_index[idx+1]]
}
