// Code generated by "stringer -type=GenerationConstraintRule -trimprefix=GenerationConstraintRule"; DO NOT EDIT.

package params

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GenerationConstraintRuleMinimum-0]
	_ = x[GenerationConstraintRuleMaxDecrease-1]
}

const _GenerationConstraintRule_name = "MinimumMaxDecrease"

var _GenerationConstraintRule_index = [...]uint8{0, 7, 18}

func (i GenerationConstraintRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GenerationConstraintRule_index)-1 {
		return "GenerationConstraintRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenerationConstraintRule_name[_GenerationConstraintRule_index[idx]:_GenerationConstraintRule_index[idx+1]]
}
