// Code generated by "stringer -type=TakeoverRule -trimprefix=TakeoverRule"; DO NOT EDIT.

package params

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TakeoverRuleForcedTakeover-0]
	_ = x[TakeoverRuleVirtualOwner-1]
}

const _TakeoverRule_name = "ForcedTakeoverVirtualOwner"

var _TakeoverRule_index = [...]uint8{0, 14, 26}

func (i TakeoverRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_TakeoverRule_index)-1 {
		return "TakeoverRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TakeoverRule_name[_TakeoverRule_index[idx]:_TakeoverRule_index[idx+1]]
}
