// Code generated by "stringer -type=WinConditionRule -trimprefix=WinConditionRule"; DO NOT EDIT.

package params

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WinConditionRuleLastFossilLoses-0]
	_ = x[WinConditionRuleRenewablePenetrationThreshold-1]
}

const _WinConditionRule_name = "LastFossilLosesRenewablePenetrationThreshold"

var _WinConditionRule_index = [...]uint8{0, 15, 44}

func (i WinConditionRule) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_WinConditionRule_index)-1 {
		return "WinConditionRule(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WinConditionRule_name[_WinConditionRule_index[idx]:_WinConditionRule_index[idx+1]]
}
