# Code generated by wasm_pybindgen; DO NOT EDIT.

import argparse
import pathlib

from ._client import JouleQuestWasm

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        usage="Validates that the wasm provides the expected API"
    )
    parser.add_argument(
        "--wasm", type=pathlib.Path, required=True, help="Path to compiled wasm binary"
    )
    args = parser.parse_args()

    with JouleQuestWasm(args.wasm) as jq:
        print(f"{args.wasm} implements the expected API")
