# Code generated by wasm_pybindgen; DO NOT EDIT.

from collections.abc import Iterable
import dataclasses
import enum
import logging
from typing import Final

import wasmtime


class ValType(enum.StrEnum):
    I32 = str(wasmtime.ValType.i32())
    I64 = str(wasmtime.ValType.i64())
    F32 = str(wasmtime.ValType.f32())
    F64 = str(wasmtime.ValType.f64())
    UNKNOWN = enum.auto()

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


@dataclasses.dataclass(frozen=True)
class FuncType:
    name: str
    params: tuple[ValType, ...]
    result: tuple[ValType, ...]

    def __str__(self) -> str:
        return f"func {self.name} ({', '.join(v.value for v in self.params)})->({', '.join(v.value for v in self.result)})"

    def matches(self, func: wasmtime.FuncType) -> bool:
        if not tuple(str(p) for p in func.params) == self.params:
            return False
        if not tuple(str(v) for v in func.results) == self.result:
            return False
        return True


_IGNORED_EXPORTS: Final = frozenset(
    ["memory", "fminimum", "fminimumf", "fmaximum", "fmaximumf", "syscall.seek"]
)


def check_exports(
    exports: Iterable[wasmtime.ExportType], expected_exports: frozenset[FuncType]
) -> None:
    found_exports = set()
    expected_funcs = {e.name: e for e in expected_exports if isinstance(e, FuncType)}
    for e in exports:
        if e.name in _IGNORED_EXPORTS:
            continue
        if isinstance(e.type, wasmtime.FuncType):
            if expectation := expected_funcs.get(e.name):
                if expectation.matches(e.type):
                    found_exports.add(expectation)
                else:
                    got = FuncType(
                        name=e.name,
                        params=tuple(ValType(str(vt)) for vt in e.type.params),
                        result=tuple(ValType(str(vt)) for vt in e.type.results),
                    )
                    logging.error(f"Got wrong type {str(got)}, want {str(expectation)}")

            else:
                logging.warning(f'Unexpected exported function "{e.name}"')
        else:
            logging.warning(f'Unexpected non-function export "{e.name}')
    if expected_exports.issubset(found_exports):
        return
    raise ValueError(
        f"Missing exports: [{',  '.join(str(exp) for exp in expected_exports.difference(found_exports))}]"
    )
