# Code generated by wasm_pybindgen; DO NOT EDIT.

import os
from typing import Final

from ._api_check import check_exports, FuncType, ValType

import wasmtime


_EXPECTED_EXPORTS: Final[frozenset[FuncType]] = frozenset(
    (
        FuncType(
            "_initialize",
            params=(),
            result=(),
        ),
        FuncType(
            "NumPlayers",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "GameStatus",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "GameReason",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "Round",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "CarbonEmissions",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerMoney",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerStatus",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerLossReason",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerRenewableAssets",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerBatteriesArbitrageAssets",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerBatteriesCapacityAssets",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerFossilsWholesaleAssets",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "PlayerFossilsCapacityAssets",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "TakeoverRenewableAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "TakeoverBatteriesArbitrageAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "TakeoverBatteriesCapacityAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "TakeoverFossilsWholesaleAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "TakeoverFossilsCapacityAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotPriceVolatility",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotGridStability",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotRenewableAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotBatteriesArbitrageAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotBatteriesCapacityAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotFossilsWholesaleAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "LastSnapshotFossilsCapacityAssets",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "PossibleActionsMask",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "CanPerformAction",
            params=(ValType.I32, ValType.I32),
            result=(ValType.I32,),
        ),
        FuncType(
            "MaxAction",
            params=(),
            result=(ValType.I32,),
        ),
        FuncType(
            "Reset",
            params=(ValType.I32,),
            result=(ValType.I32,),
        ),
        FuncType(
            "ApplyAction",
            params=(ValType.I32, ValType.I32),
            result=(ValType.I32,),
        ),
        FuncType(
            "SetRNGSeed",
            params=(ValType.I32,),
            result=(),
        ),
    )
)


class JouleQuestInstance:
    def __init__(self, store: wasmtime.Store, module: wasmtime.Module):
        self._store = store
        self._instance = wasmtime.Instance(self._store, module, ())

        self._funcs: dict[str, wasmtime.Func] = {}
        for name, val in self._instance.exports(self._store).items():
            if isinstance(val, wasmtime.Func):
                self._funcs[name] = val

        self._funcs["_initialize"](self._store)

    def num_players(self) -> int:
        return self._funcs["NumPlayers"](self._store)

    def game_status(self) -> int:
        return self._funcs["GameStatus"](self._store)

    def game_reason(self) -> int:
        return self._funcs["GameReason"](self._store)

    def round(self) -> int:
        return self._funcs["Round"](self._store)

    def carbon_emissions(self) -> int:
        return self._funcs["CarbonEmissions"](self._store)

    def player_money(self, player_index: int) -> int:
        return self._funcs["PlayerMoney"](self._store, player_index)

    def player_status(self, player_index: int) -> int:
        return self._funcs["PlayerStatus"](self._store, player_index)

    def player_loss_reason(self, player_index: int) -> int:
        return self._funcs["PlayerLossReason"](self._store, player_index)

    def player_renewable_assets(self, player_index: int) -> int:
        return self._funcs["PlayerRenewableAssets"](self._store, player_index)

    def player_batteries_arbitrage_assets(self, player_index: int) -> int:
        return self._funcs["PlayerBatteriesArbitrageAssets"](self._store, player_index)

    def player_batteries_capacity_assets(self, player_index: int) -> int:
        return self._funcs["PlayerBatteriesCapacityAssets"](self._store, player_index)

    def player_fossils_wholesale_assets(self, player_index: int) -> int:
        return self._funcs["PlayerFossilsWholesaleAssets"](self._store, player_index)

    def player_fossils_capacity_assets(self, player_index: int) -> int:
        return self._funcs["PlayerFossilsCapacityAssets"](self._store, player_index)

    def takeover_renewable_assets(self) -> int:
        return self._funcs["TakeoverRenewableAssets"](self._store)

    def takeover_batteries_arbitrage_assets(self) -> int:
        return self._funcs["TakeoverBatteriesArbitrageAssets"](self._store)

    def takeover_batteries_capacity_assets(self) -> int:
        return self._funcs["TakeoverBatteriesCapacityAssets"](self._store)

    def takeover_fossils_wholesale_assets(self) -> int:
        return self._funcs["TakeoverFossilsWholesaleAssets"](self._store)

    def takeover_fossils_capacity_assets(self) -> int:
        return self._funcs["TakeoverFossilsCapacityAssets"](self._store)

    def last_snapshot_price_volatility(self) -> int:
        return self._funcs["LastSnapshotPriceVolatility"](self._store)

    def last_snapshot_grid_stability(self) -> int:
        return self._funcs["LastSnapshotGridStability"](self._store)

    def last_snapshot_renewable_assets(self) -> int:
        return self._funcs["LastSnapshotRenewableAssets"](self._store)

    def last_snapshot_batteries_arbitrage_assets(self) -> int:
        return self._funcs["LastSnapshotBatteriesArbitrageAssets"](self._store)

    def last_snapshot_batteries_capacity_assets(self) -> int:
        return self._funcs["LastSnapshotBatteriesCapacityAssets"](self._store)

    def last_snapshot_fossils_wholesale_assets(self) -> int:
        return self._funcs["LastSnapshotFossilsWholesaleAssets"](self._store)

    def last_snapshot_fossils_capacity_assets(self) -> int:
        return self._funcs["LastSnapshotFossilsCapacityAssets"](self._store)

    def possible_actions_mask(self, player_index: int) -> int:
        return self._funcs["PossibleActionsMask"](self._store, player_index)

    def can_perform_action(self, player_index: int, action_int: int) -> int:
        return self._funcs["CanPerformAction"](self._store, player_index, action_int)

    def max_action(self) -> int:
        return self._funcs["MaxAction"](self._store)

    def reset(self, num_players: int) -> int:
        return self._funcs["Reset"](self._store, num_players)

    def apply_action(self, player_index: int, action_int: int) -> int:
        return self._funcs["ApplyAction"](self._store, player_index, action_int)

    def set_rng_seed(self, seed: int) -> None:
        return self._funcs["SetRNGSeed"](self._store, seed)


class JouleQuestWasm:
    def __init__(self, wasm_file: str | os.PathLike):
        self._store = wasmtime.Store(wasmtime.Engine(wasmtime.Config()))
        self._module = wasmtime.Module.from_file(self._store.engine, wasm_file)
        check_exports(self._module.exports, _EXPECTED_EXPORTS)

    def instance(self):
        return JouleQuestInstance(self._store, self._module)

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self._store.close()
