// Code generated by "stringer -type=ClientState -trimprefix=ClientState"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ClientStateInactive-0]
	_ = x[ClientStateUnassociated-1]
	_ = x[ClientStateAssociated-2]
	_ = x[ClientStateReady-3]
	_ = x[ClientStatePlaying-4]
}

const _ClientState_name = "InactiveUnassociatedAssociatedReadyPlaying"

var _ClientState_index = [...]uint8{0, 8, 20, 30, 35, 42}

func (i ClientState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ClientState_index)-1 {
		return "ClientState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ClientState_name[_ClientState_index[idx]:_ClientState_index[idx+1]]
}
