// Code generated by "stringer -type=GameState -trimprefix=GameState"; DO NOT EDIT.

package hub

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GameStateBlocked-0]
	_ = x[GameStateJoinable-1]
	_ = x[GameStateFull-2]
	_ = x[GameStateInProgress-3]
}

const _GameState_name = "BlockedJoinableFullInProgress"

var _GameState_index = [...]uint8{0, 7, 15, 19, 29}

func (i GameState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GameState_index)-1 {
		return "GameState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GameState_name[_GameState_index[idx]:_GameState_index[idx+1]]
}
