// Code generated by "stringer -type=AssetType -trimprefix=AssetType"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AssetTypeRenewable-0]
	_ = x[AssetTypeFossil-1]
	_ = x[AssetTypeBattery-2]
}

const _AssetType_name = "RenewableFossilBattery"

var _AssetType_index = [...]uint8{0, 9, 15, 22}

func (i AssetType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AssetType_index)-1 {
		return "AssetType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AssetType_name[_AssetType_index[idx]:_AssetType_index[idx+1]]
}
