// Code generated by "stringer -type=GridStability -trimprefix=GridStability"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GridStabilityDangerous-0]
	_ = x[GridStabilityBad-1]
	_ = x[GridStabilityOk-2]
	_ = x[GridStabilityGood-3]
}

const _GridStability_name = "DangerousBadOkGood"

var _GridStability_index = [...]uint8{0, 9, 12, 14, 18}

func (i GridStability) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_GridStability_index)-1 {
		return "GridStability(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GridStability_name[_GridStability_index[idx]:_GridStability_index[idx+1]]
}
