// Code generated by "stringer -type=PriceVolatility -trimprefix=PriceVolatility"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PriceVolatilityLow-0]
	_ = x[PriceVolatilityMedium-1]
	_ = x[PriceVolatilityHigh-2]
	_ = x[PriceVolatilityExtreme-3]
}

const _PriceVolatility_name = "LowMediumHighExtreme"

var _PriceVolatility_index = [...]uint8{0, 3, 9, 13, 20}

func (i PriceVolatility) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_PriceVolatility_index)-1 {
		return "PriceVolatility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PriceVolatility_name[_PriceVolatility_index[idx]:_PriceVolatility_index[idx+1]]
}
