//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
)

const (
	SessionCookieScopes sessionCookieContextKey = "sessionCookie.Scopes"
	XsrfHeaderScopes    xsrfHeaderContextKey    = "xsrfHeader.Scopes"
)

// Defines values for ClientState.
const (
	ClientStateAssociated   ClientState = "Associated"
	ClientStateInactive     ClientState = "Inactive"
	ClientStatePlaying      ClientState = "Playing"
	ClientStateReady        ClientState = "Ready"
	ClientStateUnassociated ClientState = "Unassociated"
)

// Valid indicates whether the value is a known member of the ClientState enum.
func (e ClientState) Valid() bool {
	switch e {
	case ClientStateAssociated:
		return true
	case ClientStateInactive:
		return true
	case ClientStatePlaying:
		return true
	case ClientStateReady:
		return true
	case ClientStateUnassociated:
		return true
	default:
		return false
	}
}

// Defines values for GameReason.
const (
	GameReasonCarbonEmissionsExceeded GameReason = "CarbonEmissionsExceeded"
	GameReasonGridUnstable            GameReason = "GridUnstable"
	GameReasonInsufficientGeneration  GameReason = "InsufficientGeneration"
	GameReasonNoActivePlayers         GameReason = "NoActivePlayers"
	GameReasonNone                    GameReason = "None"
	GameReasonUnownedTakeoverAssets   GameReason = "UnownedTakeoverAssets"
)

// Valid indicates whether the value is a known member of the GameReason enum.
func (e GameReason) Valid() bool {
	switch e {
	case GameReasonCarbonEmissionsExceeded:
		return true
	case GameReasonGridUnstable:
		return true
	case GameReasonInsufficientGeneration:
		return true
	case GameReasonNoActivePlayers:
		return true
	case GameReasonNone:
		return true
	case GameReasonUnownedTakeoverAssets:
		return true
	default:
		return false
	}
}

// Defines values for GameStatus.
const (
	Loss    GameStatus = "Loss"
	Ongoing GameStatus = "Ongoing"
	Win     GameStatus = "Win"
)

// Valid indicates whether the value is a known member of the GameStatus enum.
func (e GameStatus) Valid() bool {
	switch e {
	case Loss:
		return true
	case Ongoing:
		return true
	case Win:
		return true
	default:
		return false
	}
}

// Defines values for GameState.
const (
	Blocked    GameState = "Blocked"
	Full       GameState = "Full"
	InProgress GameState = "InProgress"
	Joinable   GameState = "Joinable"
)

// Valid indicates whether the value is a known member of the GameState enum.
func (e GameState) Valid() bool {
	switch e {
	case Blocked:
		return true
	case Full:
		return true
	case InProgress:
		return true
	case Joinable:
		return true
	default:
		return false
	}
}

// Defines values for LobbySeatState.
const (
	LobbySeatStateAssociated LobbySeatState = "Associated"
	LobbySeatStateReady      LobbySeatState = "Ready"
)

// Valid indicates whether the value is a known member of the LobbySeatState enum.
func (e LobbySeatState) Valid() bool {
	switch e {
	case LobbySeatStateAssociated:
		return true
	case LobbySeatStateReady:
		return true
	default:
		return false
	}
}

// Defines values for PlayerReason.
const (
	PlayerReasonCarbonEmissionsExceeded    PlayerReason = "CarbonEmissionsExceeded"
	PlayerReasonGridUnstable               PlayerReason = "GridUnstable"
	PlayerReasonInsufficientFunds          PlayerReason = "InsufficientFunds"
	PlayerReasonInsufficientGeneration     PlayerReason = "InsufficientGeneration"
	PlayerReasonLastPlayerWithFossilAssets PlayerReason = "LastPlayerWithFossilAssets"
	PlayerReasonNoActivePlayers            PlayerReason = "NoActivePlayers"
	PlayerReasonNone                       PlayerReason = "None"
	PlayerReasonUnownedTakeoverAssets      PlayerReason = "UnownedTakeoverAssets"
)

// Valid indicates whether the value is a known member of the PlayerReason enum.
func (e PlayerReason) Valid() bool {
	switch e {
	case PlayerReasonCarbonEmissionsExceeded:
		return true
	case PlayerReasonGridUnstable:
		return true
	case PlayerReasonInsufficientFunds:
		return true
	case PlayerReasonInsufficientGeneration:
		return true
	case PlayerReasonLastPlayerWithFossilAssets:
		return true
	case PlayerReasonNoActivePlayers:
		return true
	case PlayerReasonNone:
		return true
	case PlayerReasonUnownedTakeoverAssets:
		return true
	default:
		return false
	}
}

// Defines values for PlayerStatus.
const (
	Active PlayerStatus = "Active"
	Lost   PlayerStatus = "Lost"
)

// Valid indicates whether the value is a known member of the PlayerStatus enum.
func (e PlayerStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Lost:
		return true
	default:
		return false
	}
}

// Defines values for PlayerActionAssetType.
const (
	Battery   PlayerActionAssetType = "Battery"
	Fossil    PlayerActionAssetType = "Fossil"
	Renewable PlayerActionAssetType = "Renewable"
)

// Valid indicates whether the value is a known member of the PlayerActionAssetType enum.
func (e PlayerActionAssetType) Valid() bool {
	switch e {
	case Battery:
		return true
	case Fossil:
		return true
	case Renewable:
		return true
	default:
		return false
	}
}

// Defines values for PlayerActionType.
const (
	BuildAsset         PlayerActionType = "BuildAsset"
	Finished           PlayerActionType = "Finished"
	PledgeCapacity     PlayerActionType = "PledgeCapacity"
	ScrapAsset         PlayerActionType = "ScrapAsset"
	TakeoverAsset      PlayerActionType = "TakeoverAsset"
	TakeoverScrapAsset PlayerActionType = "TakeoverScrapAsset"
)

// Valid indicates whether the value is a known member of the PlayerActionType enum.
func (e PlayerActionType) Valid() bool {
	switch e {
	case BuildAsset:
		return true
	case Finished:
		return true
	case PledgeCapacity:
		return true
	case ScrapAsset:
		return true
	case TakeoverAsset:
		return true
	case TakeoverScrapAsset:
		return true
	default:
		return false
	}
}

// AssetMix defines model for AssetMix.
type AssetMix struct {
	BatteriesArbitrage int `json:"BatteriesArbitrage"`
	BatteriesCapacity  int `json:"BatteriesCapacity"`
	FossilsCapacity    int `json:"FossilsCapacity"`
	FossilsWholesale   int `json:"FossilsWholesale"`
	Renewables         int `json:"Renewables"`
}

// ClientSnapshot defines model for ClientSnapshot.
type ClientSnapshot struct {
	// GameID Game the client is associated with, if any
	GameID *string `json:"GameID,omitempty"`

	// ID Client ID (same value as jq_session cookie)
	ID    string      `json:"ID"`
	Name  string      `json:"Name"`
	State ClientState `json:"State"`
}

// ClientState defines model for ClientState.
type ClientState string

// CreateGameResponse defines model for CreateGameResponse.
type CreateGameResponse struct {
	GameID string `json:"GameID"`
}

// Error defines model for Error.
type Error struct {
	// Error The error message
	Error string `json:"error"`
}

// Game defines model for Game.
type Game struct {
	EmissionsCounter int `json:"EmissionsCounter"`

	// LastRoundSnapshot Summary statistics from the last round of the game
	LastRoundSnapshot struct {
		AssetMix        AssetMix `json:"AssetMix"`
		GridStability   int      `json:"GridStability"`
		PriceVolatility int      `json:"PriceVolatility"`
	} `json:"LastRoundSnapshot"`
	Players      []Player   `json:"Players"`
	Reason       GameReason `json:"Reason"`
	Round        int        `json:"Round"`
	Status       GameStatus `json:"Status"`
	TakeoverPool AssetMix   `json:"TakeoverPool"`
}

// GameReason defines model for Game.Reason.
type GameReason string

// GameStatus defines model for Game.Status.
type GameStatus string

// GameState defines model for GameState.
type GameState string

// GameView defines model for GameView.
type GameView struct {
	Game          Game   `json:"Game"`
	GameID        string `json:"GameID"`
	MyPlayerIndex int    `json:"MyPlayerIndex"`

	// PossibleActions Legal actions for the authenticated client only
	PossibleActions []PlayerAction `json:"PossibleActions"`

	// XSRFToken Send this value in the X-XSRF-Token header when posting actions for this game view
	XSRFToken string `json:"XSRFToken"`
}

// LobbyGame defines model for LobbyGame.
type LobbyGame struct {
	ID    string      `json:"ID"`
	Seats []LobbySeat `json:"Seats"`
	State GameState   `json:"State"`
}

// LobbySeat defines model for LobbySeat.
type LobbySeat struct {
	Name string `json:"Name"`

	// State Associated or Ready for lobby seats
	State LobbySeatState `json:"State"`
}

// LobbySeatState Associated or Ready for lobby seats
type LobbySeatState string

// LobbyView defines model for LobbyView.
type LobbyView struct {
	Client ClientSnapshot `json:"Client"`
	Games  []LobbyGame    `json:"Games"`
}

// Player defines model for Player.
type Player struct {
	Assets AssetMix      `json:"Assets"`
	Money  int           `json:"Money"`
	Reason *PlayerReason `json:"Reason,omitempty"`
	Status PlayerStatus  `json:"Status"`
}

// PlayerReason defines model for Player.Reason.
type PlayerReason string

// PlayerStatus defines model for Player.Status.
type PlayerStatus string

// PlayerAction defines model for PlayerAction.
type PlayerAction struct {
	AssetType   *PlayerActionAssetType `json:"AssetType,omitempty"`
	Cost        *int                   `json:"Cost,omitempty"`
	PlayerIndex int                    `json:"PlayerIndex"`
	Type        PlayerActionType       `json:"Type"`
}

// PlayerActionAssetType defines model for PlayerAction.AssetType.
type PlayerActionAssetType string

// PlayerActionType defines model for PlayerAction.Type.
type PlayerActionType string

// SetClientNameRequest defines model for SetClientNameRequest.
type SetClientNameRequest struct {
	Name string `json:"Name"`
}

// GameID defines model for GameID.
type GameID = string

// ErrorResponse defines model for errorResponse.
type ErrorResponse = Error

// sessionCookieContextKey is the context key for sessionCookie security scheme
type sessionCookieContextKey string

// xsrfHeaderContextKey is the context key for xsrfHeader security scheme
type xsrfHeaderContextKey string

// PostApiClientNameJSONRequestBody defines body for PostApiClientName for application/json ContentType.
type PostApiClientNameJSONRequestBody = SetClientNameRequest

// PostApiGGameIdActionJSONRequestBody defines body for PostApiGGameIdAction for application/json ContentType.
type PostApiGGameIdActionJSONRequestBody = PlayerAction

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/client/name)
	PostApiClientName(w http.ResponseWriter, r *http.Request)

	// (POST /api/g/{gameId}/action)
	PostApiGGameIdAction(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (POST /api/g/{gameId}/exit)
	PostApiGGameIdExit(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (GET /api/g/{gameId}/view)
	GetApiGGameIdView(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (GET /api/lobby)
	GetApiLobby(w http.ResponseWriter, r *http.Request)

	// (POST /api/lobby/games)
	PostApiLobbyGames(w http.ResponseWriter, r *http.Request)

	// (POST /api/lobby/games/{gameId}/join)
	PostApiLobbyGamesGameIdJoin(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (POST /api/lobby/games/{gameId}/leave)
	PostApiLobbyGamesGameIdLeave(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (POST /api/lobby/games/{gameId}/ready)
	PostApiLobbyGamesGameIdReady(w http.ResponseWriter, r *http.Request, gameId GameID)

	// (POST /api/lobby/games/{gameId}/unready)
	PostApiLobbyGamesGameIdUnready(w http.ResponseWriter, r *http.Request, gameId GameID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostApiClientName operation middleware
func (siw *ServerInterfaceWrapper) PostApiClientName(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiClientName(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiGGameIdAction operation middleware
func (siw *ServerInterfaceWrapper) PostApiGGameIdAction(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	ctx = context.WithValue(ctx, XsrfHeaderScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiGGameIdAction(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiGGameIdExit operation middleware
func (siw *ServerInterfaceWrapper) PostApiGGameIdExit(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiGGameIdExit(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiGGameIdView operation middleware
func (siw *ServerInterfaceWrapper) GetApiGGameIdView(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiGGameIdView(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetApiLobby operation middleware
func (siw *ServerInterfaceWrapper) GetApiLobby(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetApiLobby(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLobbyGames operation middleware
func (siw *ServerInterfaceWrapper) PostApiLobbyGames(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLobbyGames(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLobbyGamesGameIdJoin operation middleware
func (siw *ServerInterfaceWrapper) PostApiLobbyGamesGameIdJoin(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLobbyGamesGameIdJoin(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLobbyGamesGameIdLeave operation middleware
func (siw *ServerInterfaceWrapper) PostApiLobbyGamesGameIdLeave(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLobbyGamesGameIdLeave(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLobbyGamesGameIdReady operation middleware
func (siw *ServerInterfaceWrapper) PostApiLobbyGamesGameIdReady(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLobbyGamesGameIdReady(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostApiLobbyGamesGameIdUnready operation middleware
func (siw *ServerInterfaceWrapper) PostApiLobbyGamesGameIdUnready(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "gameId" -------------
	var gameId GameID

	err = runtime.BindStyledParameterWithOptions("simple", "gameId", r.PathValue("gameId"), &gameId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "gameId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, SessionCookieScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostApiLobbyGamesGameIdUnready(w, r, gameId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/client/name", wrapper.PostApiClientName)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/g/{gameId}/action", wrapper.PostApiGGameIdAction)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/g/{gameId}/exit", wrapper.PostApiGGameIdExit)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/g/{gameId}/view", wrapper.GetApiGGameIdView)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/api/lobby", wrapper.GetApiLobby)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/lobby/games", wrapper.PostApiLobbyGames)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/lobby/games/{gameId}/join", wrapper.PostApiLobbyGamesGameIdJoin)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/lobby/games/{gameId}/leave", wrapper.PostApiLobbyGamesGameIdLeave)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/lobby/games/{gameId}/ready", wrapper.PostApiLobbyGamesGameIdReady)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/api/lobby/games/{gameId}/unready", wrapper.PostApiLobbyGamesGameIdUnready)

	return m
}
