// Code generated by "stringer -type=MarketMode -trimprefix=MarketMode"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MarketModeCapacity-0]
	_ = x[MarketModeWholesale-1]
	_ = x[MarketModeArbitrage-2]
}

const _MarketMode_name = "CapacityWholesaleArbitrage"

var _MarketMode_index = [...]uint8{0, 8, 17, 26}

func (i MarketMode) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MarketMode_index)-1 {
		return "MarketMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MarketMode_name[_MarketMode_index[idx]:_MarketMode_index[idx+1]]
}
