// Code generated by "stringer -type=OperationMode -trimprefix=OperationMode"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationModeCapacity-1]
	_ = x[OperationModeForecastingService-2]
	_ = x[OperationModeApplyCarbonTax-4]
}

const (
	_OperationMode_name_0 = "CapacityForecastingService"
	_OperationMode_name_1 = "ApplyCarbonTax"
)

var (
	_OperationMode_index_0 = [...]uint8{0, 8, 26}
)

func (i OperationMode) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _OperationMode_name_0[_OperationMode_index_0[i]:_OperationMode_index_0[i+1]]
	case i == 4:
		return _OperationMode_name_1
	default:
		return "OperationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
