// Code generated by "stringer -type=OperationMode -trimprefix=OperationMode"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OperationModeCapacity-1]
}

const _OperationMode_name = "Capacity"

var _OperationMode_index = [...]uint8{0, 8}

func (i OperationMode) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_OperationMode_index)-1 {
		return "OperationMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperationMode_name[_OperationMode_index[idx]:_OperationMode_index[idx+1]]
}
