// Code generated by "stringer -type=Policy -trimprefix=Policy"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PolicyNone-0]
	_ = x[PolicyCarbonTax-1]
}

const _Policy_name = "NoneCarbonTax"

var _Policy_index = [...]uint8{0, 4, 13}

func (i Policy) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Policy_index)-1 {
		return "Policy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Policy_name[_Policy_index[idx]:_Policy_index[idx+1]]
}
