// Code generated by "stringer -type=Service -trimprefix=Service"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServiceNone-0]
	_ = x[ServicePriceForecast-1]
}

const _Service_name = "NonePriceForecast"

var _Service_index = [...]uint8{0, 4, 17}

func (i Service) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Service_index)-1 {
		return "Service(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Service_name[_Service_index[idx]:_Service_index[idx+1]]
}
