// Code generated by "stringer -type=Type -trimprefix=Type"; DO NOT EDIT.

package assets

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeRenewable-0]
	_ = x[TypeFossil-1]
	_ = x[TypeBattery-2]
}

const _Type_name = "RenewableFossilBattery"

var _Type_index = [...]uint8{0, 9, 15, 22}

func (i Type) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Type_index)-1 {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[idx]:_Type_index[idx+1]]
}
